/* Account Module */
export const UPDATE_AUTHSTATE = 'UPDATE_AUTHSTATE';
export const SET_USER = 'SET_USER';
export const SET_FINGERPRINT = 'SET_FINGERPRINT';

/* Funds Module */
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_ALL_BALANCES = 'SET_ALL_BALANCES';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';

/* Modals Module */
export const SHOW_WITHDRWAL_MODAL = 'SHOW_WITHDRWAL_MODAL';
export const HIDE_WITHDRAWAL_MODAL = 'HIDE_WITHDRAWAL_MODAL';
export const SHOW_DEPOSIT_MODAL = 'SHOW_DEPOSIT_MODAL';
export const HIDE_DEPOSIT_MODAL = 'HIDE_DEPOSIT_MODAL';
