/* Account Module */
export const UPDATE_AUTHSTATE = 'UPDATE_AUTHSTATE';
export const SET_USER = 'SET_USER';
export const SET_FINGERPRINT = 'SET_FINGERPRINT';

/* Funds Module */
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_ALL_BALANCES = 'SET_ALL_BALANCES';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';

/* Modals Module */
export const SHOW_WITHDRWAL_MODAL = 'SHOW_WITHDRWAL_MODAL';
export const HIDE_WITHDRAWAL_MODAL = 'HIDE_WITHDRAWAL_MODAL';
export const SHOW_DEPOSIT_MODAL = 'SHOW_DEPOSIT_MODAL';
export const HIDE_DEPOSIT_MODAL = 'HIDE_DEPOSIT_MODAL';

/* Dice Module */
export const SET_DICE_STATE = 'SET_DICE_STATE';
export const DISABLE_DICE_BETTING = 'DISABLE_DICE_BETTING';
export const ENABLE_DICE_BETTING = 'ENABLE_DICE_BETTING';
export const ADD_DICE_BET = 'ADD_DICE_BET';
export const SET_DICE_CLIENT_SEED = 'SET_DICE_CLIENT_SEED';
export const SET_DICE_NONCE = 'SET_DICE_NONCE';
export const UPDATE_PREVIOUS_AND_CURRENT_DICE_SEED = 'UPDATE_PREVIOUS_AND_CURRENT_DICE_SEED';
export const SET_AUTO_BET_MODE = 'SET_AUTO_BET_MODE';
export const SET_AUTO_BET_STARTED = 'SET_AUTO_BET_STARTED';
export const SET_AUTO_BET_SETTINGS = 'SET_AUTO_BET_SETTINGS';
