// Account
export const UPDATE_AUTHSTATE = 'UPDATE_AUTHSTATE';
export const SET_USER = 'SET_USER';
export const SET_FINGERPRINT = 'SET_FINGERPRINT';

// Funds
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_ALL_BALANCES = 'SET_ALL_BALANCES';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_ACTIVE_CURRENCY = 'SET_ACTIVE_CURRENCY';

// Modals
export const SHOW_WITHDRWAL_MODAL = 'SHOW_WITHDRWAL_MODAL';
export const HIDE_WITHDRAWAL_MODAL = 'HIDE_WITHDRAWAL_MODAL';
export const SHOW_DEPOSIT_MODAL = 'SHOW_DEPOSIT_MODAL';
export const HIDE_DEPOSIT_MODAL = 'HIDE_DEPOSIT_MODAL';

// Dice
export const SET_DICE_STATE = 'SET_DICE_STATE';
export const DISABLE_DICE_BETTING = 'DISABLE_DICE_BETTING';
export const ENABLE_DICE_BETTING = 'ENABLE_DICE_BETTING';
export const ADD_DICE_BET = 'ADD_DICE_BET';
export const SET_DICE_CLIENT_SEED = 'SET_DICE_CLIENT_SEED';
export const SET_DICE_NONCE = 'SET_DICE_NONCE';
export const UPDATE_PREVIOUS_AND_CURRENT_DICE_SEED = 'UPDATE_PREVIOUS_AND_CURRENT_DICE_SEED';
export const SET_AUTO_BET_MODE = 'SET_AUTO_BET_MODE';
export const SET_AUTO_BET_STARTED = 'SET_AUTO_BET_STARTED';
export const SET_AUTO_BET_SETTINGS = 'SET_AUTO_BET_SETTINGS';

// Stats
export const SET_BET_STATS = 'SET_BET_STATS';
export const SET_SITE_STATS = 'SET_SITE_STATS';
export const SET_ALL_BETS = 'SET_ALL_BETS';
export const SET_HIGHROLLER_BETS = 'SET_HIGHROLLER_BETS';
export const SET_EXCHANGE_RATES = 'SET_EXCHANGE_RATES';
export const SET_WON_LAST_24HOURS = 'SET_WON_LAST_24HOURS';

// Socket
export const SET_WEBSOCKET = 'SET_WEBSOCKET';
export const SET_SOCKET_CONNECTION = 'SET_SOCKET_CONNECTION';
export const SET_SOCKET_RECONNECTION_COUNT = 'SET_SOCKET_RECONNECTION_COUNT';
export const SET_WATCH_BETS_WEBSOCKET = 'SET_WATCH_BETS_WEBSOCKET';
export const ADD_TO_HIGHROLLER_BETS = 'ADD_TO_HIGHROLLER_BETS';
export const ADD_TO_HIGHROLLER_BETS_IN_CHAT = 'ADD_TO_HIGHROLLER_BETS_IN_CHAT';
export const ADD_TO_ALL_BETS = 'ADD_TO_ALL_BETS';
export const SET_WATCH_BETS_PAUSED = 'SET_WATCH_BETS_PAUSED';
export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';
export const SET_CHAT_ANONYMOUS_USER_COUNT = 'SET_CHAT_ANONYMOUS_USER_COUNT';
export const ADD_CHAT_NEW_USER = 'ADD_CHAT_NEW_USER';
export const DELETE_CHAT_USER = 'DELETE_CHAT_USER';
export const SET_BANNED_USERNAMES = 'SET_BANNED_USERNAMES';
export const CLEAR_ALL_CHAT = 'CLEAR_ALL_CHAT';
export const CLEAR_USERS_CHAT = 'CLEAR_USERS_CHAT';
export const SET_MODERATORS = 'SET_MODERATORS';
export const SET_IS_CHAT_MODERATOR = 'SET_IS_CHAT_MODERATOR';
export const SET_IS_CHAT_OPENED = 'SET_IS_CHAT_OPENED';
